import type { Tool } from "./types";

export type FaqItem = {
  q: Record<"en" | "fr", string>;
  a: Record<"en" | "fr", string>;
};

function universal(name: Record<"en" | "fr", string>, isNetwork: boolean): FaqItem[] {
  return [
    {
      q: { en: `Is ${name.en} free to use?`, fr: `${name.fr} est-il gratuit ?` },
      a: {
        en: "Yes, completely free — no account, no signup, no hidden fees.",
        fr: "Oui, entièrement gratuit — sans compte, sans inscription, sans frais cachés.",
      },
    },
    {
      q: {
        en: isNetwork ? "Is my data stored on your servers?" : "Are my files uploaded to a server?",
        fr: isNetwork ? "Mes données sont-elles stockées sur vos serveurs ?" : "Mes fichiers sont-ils téléchargés sur un serveur ?",
      },
      a: {
        en: isNetwork
          ? "A request passes through our proxy to fetch external data. Nothing you enter is stored in a database. Standard server access logs (IP address, timestamp) are retained for ~30 days for security purposes — see our privacy policy."
          : "No. All processing happens locally in your browser. Your files never leave your device.",
        fr: isNetwork
          ? "Une requête transite par notre proxy pour récupérer des données externes. Vos saisies ne sont pas stockées en base de données. Les logs d'accès HTTP standard (adresse IP, horodatage) sont conservés environ 30 jours à des fins de sécurité — voir notre politique de confidentialité."
          : "Non. Tout le traitement s'effectue localement dans votre navigateur. Vos fichiers ne quittent jamais votre appareil.",
      },
    },
    {
      q: {
        en: `Does ${name.en} work offline?`,
        fr: `${name.fr} fonctionne-t-il hors ligne ?`,
      },
      a: {
        en: isNetwork
          ? "No — an internet connection is required to fetch external data."
          : "Yes — once the page has loaded, the tool works entirely offline.",
        fr: isNetwork
          ? "Non — une connexion internet est requise pour récupérer les données externes."
          : "Oui — une fois la page chargée, l'outil fonctionne entièrement hors ligne.",
      },
    },
  ];
}

const SPECIFIC: Partial<Record<string, FaqItem[]>> = {
  "json-formatter": [
    { q: { en: "Does it validate JSON strictly?", fr: "Valide-t-il le JSON strictement ?" }, a: { en: "Yes — it follows RFC 8259 and flags any syntax error with the exact line number.", fr: "Oui — il suit la norme RFC 8259 et signale toute erreur de syntaxe avec le numéro de ligne exact." } },
    { q: { en: "Can it handle large or deeply nested JSON?", fr: "Peut-il gérer du JSON volumineux ou profondément imbriqué ?" }, a: { en: "Yes. The formatter handles arbitrarily large and deeply nested JSON. Performance depends on your device, but files up to several megabytes format instantly in most modern browsers.", fr: "Oui. Le formateur gère des JSON arbitrairement grands et profondément imbriqués. Les performances dépendent de votre appareil, mais des fichiers de plusieurs mégaoctets se formatent instantanément dans la plupart des navigateurs modernes." } },
  ],
  "image-converter": [
    { q: { en: "What image formats are supported?", fr: "Quels formats d'image sont supportés ?" }, a: { en: "JPG, PNG, WebP and AVIF — with optional resize and quality control for each export.", fr: "JPG, PNG, WebP et AVIF — avec redimensionnement et contrôle qualité optionnels à l'export." } },
    { q: { en: "Can I resize the image at the same time as converting it?", fr: "Puis-je redimensionner l'image en même temps que la conversion ?" }, a: { en: "Yes. Before downloading, you can set a target width or height and adjust the export quality. The aspect ratio is preserved by default.", fr: "Oui. Avant le téléchargement, vous pouvez définir une largeur ou hauteur cible et ajuster la qualité d'export. Le ratio d'aspect est conservé par défaut." } },
  ],
  "pdf-converter": [{ q: { en: "What can I convert a PDF to?", fr: "En quoi puis-je convertir un PDF ?" }, a: { en: "You can export each page as a PNG or JPG image, or convert the entire document to a DOCX Word file.", fr: "Vous pouvez exporter chaque page en image PNG ou JPG, ou convertir l'intégralité du document en fichier Word DOCX." } }],
  "audio-converter": [{ q: { en: "Why does the first conversion take longer?", fr: "Pourquoi la première conversion prend-elle plus de temps ?" }, a: { en: "The FFmpeg WebAssembly engine (~20 MB) needs to load once. Subsequent conversions are instant.", fr: "Le moteur FFmpeg WebAssembly (~20 Mo) doit se charger une fois. Les conversions suivantes sont instantanées." } }],
  "video-converter": [{ q: { en: "Can I extract audio from a video?", fr: "Puis-je extraire l'audio d'une vidéo ?" }, a: { en: "Yes — choose MP3 or WAV as the output format and the tool will extract the audio track.", fr: "Oui — choisissez MP3 ou WAV comme format de sortie et l'outil extraira la piste audio." } }],
  "pdf-merge": [
    { q: { en: "Is there a limit on the number of PDFs I can merge?", fr: "Y a-t-il une limite sur le nombre de PDF à fusionner ?" }, a: { en: "You can merge as many files as your device's memory allows — tested up to 20+ files in most browsers without issue.", fr: "Vous pouvez fusionner autant de fichiers que la mémoire de votre appareil le permet — testé avec plus de 20 fichiers dans la plupart des navigateurs sans problème." } },
    { q: { en: "Can I reorder the PDFs before merging?", fr: "Puis-je réordonner les PDF avant de les fusionner ?" }, a: { en: "Yes. After adding your files, drag and drop them to set the order before generating the merged document.", fr: "Oui. Après avoir ajouté vos fichiers, glissez-déposez-les pour définir l'ordre avant de générer le document fusionné." } },
  ],
  "qr-generator": [
    { q: { en: "What types of content can I encode in a QR code?", fr: "Quels types de contenu puis-je encoder dans un QR code ?" }, a: { en: "URLs, plain text, email addresses and phone numbers — any of these can be encoded into a scannable QR code instantly.", fr: "URL, texte brut, adresses e-mail et numéros de téléphone — n'importe lequel de ces contenus peut être encodé en un QR code scannable instantanément." } },
    { q: { en: "What formats can I download the QR code in?", fr: "Dans quels formats puis-je télécharger le QR code ?" }, a: { en: "SVG (vector, scales to any size) or PNG (raster, for embedding in images and documents).", fr: "SVG (vectoriel, s'adapte à n'importe quelle taille) ou PNG (matriciel, pour intégration dans des images et des documents)." } },
    { q: { en: "Do QR codes generated here expire?", fr: "Les QR codes générés ici expirent-ils ?" }, a: { en: "No. QR codes are a static encoding of your content — no expiry date, no server required to stay active. A QR code generated today will still work in ten years.", fr: "Non. Un QR code est un encodage statique de votre contenu — aucune date d'expiration, aucun serveur requis pour rester actif. Un QR code généré aujourd'hui fonctionnera encore dans dix ans." } },
  ],
  "base64": [{ q: { en: "Can I encode binary files, not just text?", fr: "Puis-je encoder des fichiers binaires, pas seulement du texte ?" }, a: { en: "Yes — drop any file (image, PDF, archive…) and get its Base64 representation.", fr: "Oui — déposez n'importe quel fichier (image, PDF, archive…) et obtenez sa représentation Base64." } }],
  "markdown-html": [{ q: { en: "Which Markdown flavour is supported?", fr: "Quelle variante de Markdown est supportée ?" }, a: { en: "CommonMark and GitHub Flavored Markdown (GFM) — including tables, task lists and strikethrough.", fr: "CommonMark et GitHub Flavored Markdown (GFM) — y compris les tableaux, les listes de tâches et le texte barré." } }],
  "hash-generator": [{ q: { en: "Can I hash a file, not just text?", fr: "Puis-je hasher un fichier, pas seulement du texte ?" }, a: { en: "Yes — drag and drop any file to compute its MD5, SHA-1 and SHA-256 fingerprints simultaneously.", fr: "Oui — glissez-déposez n'importe quel fichier pour calculer simultanément ses empreintes MD5, SHA-1 et SHA-256." } }],
  "regex-tester": [{ q: { en: "Which regex flags are supported?", fr: "Quels flags regex sont supportés ?" }, a: { en: "g (global), i (case-insensitive), m (multiline), s (dotAll) and u (unicode) — plus named capture groups.", fr: "g (global), i (insensible à la casse), m (multilignes), s (dotAll) et u (unicode) — ainsi que les groupes de capture nommés." } }],
  "ip-lookup": [{ q: { en: "Why might the location be inaccurate?", fr: "Pourquoi la localisation peut-elle être imprécise ?" }, a: { en: "GeoIP databases have a natural margin of error, especially for mobile networks and VPN exit nodes.", fr: "Les bases de données GeoIP ont une marge d'erreur naturelle, notamment pour les réseaux mobiles et les nœuds de sortie VPN." } }],
  "uuid-generator": [{ q: { en: "What is the difference between UUID v1, v4 and v7?", fr: "Quelle est la différence entre UUID v1, v4 et v7 ?" }, a: { en: "v1 embeds a timestamp and MAC address; v4 is fully random; v7 is time-ordered random — ideal for sortable primary keys.", fr: "v1 intègre un horodatage et une adresse MAC ; v4 est entièrement aléatoire ; v7 est ordonné dans le temps et aléatoire — idéal pour les clés primaires triables." } }],
  "cron-generator": [{ q: { en: "Does it support non-standard cron shortcuts?", fr: "Supporte-t-il les raccourcis cron non standards ?" }, a: { en: "Yes — @hourly, @daily, @weekly, @monthly and @yearly are all supported alongside standard 5-field syntax.", fr: "Oui — @hourly, @daily, @weekly, @monthly et @yearly sont tous supportés en plus de la syntaxe standard à 5 champs." } }],
  "case-converter": [{ q: { en: "What case formats are available?", fr: "Quels formats de casse sont disponibles ?" }, a: { en: "UPPER CASE, lower case, Title Case, Sentence case, camelCase, PascalCase, snake_case and kebab-case.", fr: "MAJUSCULE, minuscule, Titre, Phrase, camelCase, PascalCase, snake_case et kebab-case." } }],
  "word-counter": [{ q: { en: "How is reading time estimated?", fr: "Comment le temps de lecture est-il estimé ?" }, a: { en: "Based on an average adult reading speed of 200 words per minute.", fr: "Sur la base d'une vitesse de lecture adulte moyenne de 200 mots par minute." } }],
  "remove-linebreaks": [{ q: { en: "Can I preserve paragraph breaks while removing single line breaks?", fr: "Puis-je conserver les sauts de paragraphe tout en supprimant les sauts de ligne simples ?" }, a: { en: "Yes — the tool preserves double line breaks (paragraph separators) while removing single ones.", fr: "Oui — l'outil conserve les doubles sauts de ligne (séparateurs de paragraphe) tout en supprimant les simples." } }],
  "text-reverser": [{ q: { en: "Does it handle emojis and Unicode correctly?", fr: "Gère-t-il correctement les emojis et l'Unicode ?" }, a: { en: "Yes — it uses proper Unicode segmentation so emojis and combining characters are treated as single units.", fr: "Oui — il utilise une segmentation Unicode correcte pour que les emojis et les caractères combinants soient traités comme des unités simples." } }],
  "url-encoder": [{ q: { en: "What is the difference between encoding a full URL and a component?", fr: "Quelle est la différence entre l'encodage d'une URL complète et d'un composant ?" }, a: { en: "Full URL encoding preserves slashes and structure; component encoding treats the entire string as a value and encodes everything including slashes.", fr: "L'encodage d'URL complète préserve les barres obliques et la structure ; l'encodage de composant encode tout, y compris les barres obliques." } }],
  "html-entities": [{ q: { en: "Which characters get encoded?", fr: "Quels caractères sont encodés ?" }, a: { en: "< > & \" ' and accented or special characters — using named entities where available, numeric entities otherwise.", fr: "< > & \" ' et les caractères accentués ou spéciaux — en utilisant des entités nommées lorsqu'elles sont disponibles, des entités numériques sinon." } }],
  "palette-generator": [{ q: { en: "What harmony modes are available?", fr: "Quels modes d'harmonie sont disponibles ?" }, a: { en: "Complementary, triadic, analogous and split-complementary — each producing a different balanced color set.", fr: "Complémentaire, triadique, analogue et complémentaire fractionnée — chacun produisant un ensemble de couleurs équilibré différent." } }],
  "password-generator": [
    { q: { en: "Is the generated password truly random?", fr: "Le mot de passe généré est-il vraiment aléatoire ?" }, a: { en: "Yes — it uses the Web Crypto API which draws from your OS's cryptographically secure random number generator.", fr: "Oui — il utilise la Web Crypto API qui s'appuie sur le générateur de nombres aléatoires cryptographiquement sécurisé de votre système d'exploitation." } },
    { q: { en: "Can I generate passwords that meet specific complexity requirements?", fr: "Puis-je générer des mots de passe répondant à des exigences de complexité spécifiques ?" }, a: { en: "Yes. Set the length and independently toggle uppercase, lowercase, numbers and symbols to match any password policy — for example, 16 characters with at least one symbol and one number.", fr: "Oui. Définissez la longueur et activez indépendamment majuscules, minuscules, chiffres et symboles pour correspondre à n'importe quelle politique de mot de passe — par exemple, 16 caractères avec au moins un symbole et un chiffre." } },
  ],
  "gradient-generator": [{ q: { en: "How many color stops can I add?", fr: "Combien d'arrêts de couleur puis-je ajouter ?" }, a: { en: "Up to 5 color stops — enough to create rich, multi-tone gradients.", fr: "Jusqu'à 5 arrêts de couleur — suffisant pour créer des dégradés riches à plusieurs tons." } }],
  "meta-preview": [{ q: { en: "Which platforms does the preview simulate?", fr: "Quelles plateformes la prévisualisation simule-t-elle ?" }, a: { en: "Google search snippet, Facebook Open Graph card and Twitter/X card — all rendered simultaneously.", fr: "L'extrait de recherche Google, la carte Open Graph Facebook et la carte Twitter/X — tous rendus simultanément." } }],
  "seo-analyzer": [{ q: { en: "What criteria does the SEO score cover?", fr: "Quels critères le score SEO couvre-t-il ?" }, a: { en: "Title length and keywords, meta description quality, H1–H6 heading structure, word count and image alt attributes.", fr: "Longueur et mots-clés du titre, qualité de la meta description, structure des titres H1–H6, nombre de mots et attributs alt des images." } }],
  "border-radius": [
    { q: { en: "Why does a 50% radius look oval instead of round?", fr: "Pourquoi un rayon à 50% donne une forme ovale et pas ronde ?" }, a: { en: "Because the percentage is computed against the element's own width for the horizontal radius and its own height for the vertical radius. On a square element both are equal, so you get a circle. On a rectangle they differ, so the corner curve becomes an ellipse.", fr: "Parce que le pourcentage se calcule par rapport à la largeur de l'élément pour le rayon horizontal, et à sa hauteur pour le rayon vertical. Sur un élément carré, les deux sont égaux, donc on obtient un cercle. Sur un rectangle, ils diffèrent, et la courbe du coin devient une ellipse." } },
    { q: { en: "Is border-radius the same as an iOS-style squircle icon?", fr: "border-radius produit-il la même courbe que les icônes squircle d'iOS ?" }, a: { en: "Not exactly. iOS app icons use a superellipse curve, which is mathematically smoother between the flat edge and the corner than a standard CSS border-radius arc. Border-radius gets visually close at high values but won't match pixel-for-pixel.", fr: "Pas exactement. Les icônes iOS utilisent une courbe superellipse, mathématiquement plus douce entre le bord plat et le coin qu'un arc CSS border-radius classique. border-radius s'en approche visuellement à forte valeur, mais sans correspondance pixel pour pixel." } },
  ],
  "timestamp": [
    { q: { en: "Why does my timestamp show a date thousands of years in the future?", fr: "Pourquoi mon timestamp affiche-t-il une date des milliers d'années dans le futur ?" }, a: { en: "You most likely pasted a millisecond timestamp (13 digits) into a field expecting seconds (10 digits). A millisecond value read as seconds is 1000× too large, which pushes the date far into the future. Divide it by 1000 first.", fr: "Vous avez probablement collé un timestamp en millisecondes (13 chiffres) dans un champ attendant des secondes (10 chiffres). Une valeur en millisecondes lue comme des secondes est 1000 fois trop grande, ce qui projette la date très loin dans le futur. Divisez-la d'abord par 1000." } },
    { q: { en: "Does the Unix timestamp have a maximum value like the Y2K bug?", fr: "Le timestamp Unix a-t-il une valeur maximale, comme le bug de l'an 2000 ?" }, a: { en: "Yes, but it doesn't affect this tool. Classic 32-bit signed Unix time overflows on January 19, 2038 — a real limit on some older C systems and pre-8.0 MySQL TIMESTAMP columns. JavaScript's Date object stores milliseconds as a 64-bit number, so timestamps here are safe well beyond that date.", fr: "Oui, mais ça n'affecte pas cet outil. Le temps Unix classique en 32 bits signés déborde le 19 janvier 2038 — une vraie limite sur certains vieux systèmes C et les colonnes MySQL TIMESTAMP antérieures à la version 8.0. L'objet Date de JavaScript stocke les millisecondes sur 64 bits, donc les timestamps ici restent fiables bien au-delà de cette date." } },
  ],
  "favicon-generator": [
    { q: { en: "Is the downloaded .ico file a real ICO format?", fr: "Le fichier .ico téléchargé est-il un vrai format ICO ?" }, a: { en: "No — it's a PNG image renamed with an .ico extension. Browsers read it correctly when linked with <link rel=\"icon\">, but if you need a true multi-size ICO container (some legacy Windows contexts require it), use a dedicated ICO packer instead.", fr: "Non — c'est une image PNG renommée avec l'extension .ico. Les navigateurs la lisent correctement via <link rel=\"icon\">, mais si vous avez besoin d'un vrai conteneur ICO multi-tailles (certains contextes Windows anciens l'exigent), utilisez un packer ICO dédié." } },
    { q: { en: "Can I use more than two characters?", fr: "Puis-je utiliser plus de deux caractères ?" }, a: { en: "The input is capped at two characters by design — favicons render at 16px in most browser tabs, and anything beyond two characters becomes unreadable at that size regardless of font weight.", fr: "La saisie est volontairement limitée à deux caractères — les favicons s'affichent à 16px dans la plupart des onglets de navigateur, et au-delà de deux caractères, le texte devient illisible à cette taille quelle que soit la graisse." } },
  ],
  "jwt-decoder": [
    { q: { en: "Does this tool verify if the JWT signature is valid?", fr: "Cet outil vérifie-t-il que la signature du JWT est valide ?" }, a: { en: "No, and that's intentional — verifying requires the secret key (HS256) or public key (RS256) used to sign the token, which this tool never asks for. It only decodes the header and payload so you can read the claims; treat an unverified token as untrusted.", fr: "Non, et c'est volontaire — la vérification nécessite la clé secrète (HS256) ou la clé publique (RS256) utilisée pour signer le token, que cet outil ne demande jamais. Il décode uniquement le header et le payload pour lire les claims ; considérez un token non vérifié comme non fiable." } },
    { q: { en: "Why does the tool show a sample token by default?", fr: "Pourquoi l'outil affiche-t-il un token d'exemple par défaut ?" }, a: { en: "It preloads the well-known jwt.io demo token (an HS256 token with sub, name and iat/exp claims) so you can see the decoded output immediately, without needing a real token on hand first.", fr: "Il précharge le token de démo connu de jwt.io (un token HS256 avec des claims sub, name et iat/exp) pour que vous voyiez le résultat décodé immédiatement, sans avoir besoin d'un vrai token sous la main." } },
  ],
  "robots-txt": [
    { q: { en: "Does Disallow in robots.txt actually hide a page from search results?", fr: "Une règle Disallow dans robots.txt masque-t-elle vraiment une page des résultats de recherche ?" }, a: { en: "Not reliably. A well-behaved crawler won't crawl the disallowed path, but the URL can still get indexed (without its content) if other sites link to it, and robots.txt itself is publicly readable — so a Disallow rule reveals the path rather than hiding it. Use noindex meta tags or authentication for pages that must stay out of results or off-limits.", fr: "Pas de façon fiable. Un crawler respectueux ne va pas explorer le chemin exclu, mais l'URL peut quand même être indexée (sans son contenu) si d'autres sites y font un lien, et robots.txt lui-même est lisible publiquement — une règle Disallow révèle donc le chemin plutôt que de le cacher. Utilisez une balise meta noindex ou une authentification pour les pages qui doivent vraiment rester hors des résultats ou inaccessibles." } },
    { q: { en: "Where does the finished robots.txt file need to go?", fr: "Où faut-il placer le fichier robots.txt une fois généré ?" }, a: { en: "At the root of the domain — https://example.com/robots.txt — not in a subdirectory. A file placed at https://example.com/blog/robots.txt is ignored by every major crawler; only the root location is checked.", fr: "À la racine du domaine — https://example.com/robots.txt — pas dans un sous-répertoire. Un fichier placé à https://example.com/blog/robots.txt est ignoré par tous les crawlers majeurs ; seul l'emplacement racine est vérifié." } },
  ],
  "base-converter": [
    { q: { en: "Can I convert negative numbers?", fr: "Puis-je convertir des nombres négatifs ?" }, a: { en: "No — the input is treated as an unsigned integer. There's no two's-complement handling, so a negative value won't produce the binary representation a programming language would generate internally.", fr: "Non — la saisie est traitée comme un entier non signé. Il n'y a pas de gestion du complément à deux, donc une valeur négative ne produira pas la représentation binaire qu'un langage de programmation générerait en interne." } },
    { q: { en: "Why does hex use letters A–F?", fr: "Pourquoi l'hexadécimal utilise-t-il les lettres A à F ?" }, a: { en: "Because base 16 needs sixteen distinct digits and decimal only supplies ten (0–9). A through F fill the remaining six values (10 through 15) — so hex FF equals decimal 255, the maximum value a single byte can hold.", fr: "Parce que la base 16 a besoin de seize chiffres distincts et le décimal n'en fournit que dix (0 à 9). A à F comblent les six valeurs restantes (10 à 15) — donc FF en hexadécimal équivaut à 255 en décimal, la valeur maximale qu'un seul octet peut contenir." } },
  ],
  "box-shadow": [
    { q: { en: "What does a negative spread value actually do?", fr: "Que fait réellement une valeur de spread négative ?" }, a: { en: "It shrinks the shadow's box before the blur is applied, pulling the shadow in tighter than the element itself. Combined with a larger blur, this is how you get a soft shadow that doesn't visibly extend past the element's edges.", fr: "Elle réduit la boîte de l'ombre avant que le flou ne soit appliqué, resserrant l'ombre plus près que l'élément lui-même. Combiné à un flou plus large, c'est ainsi qu'on obtient une ombre douce qui ne déborde pas visiblement des bords de l'élément." } },
    { q: { en: "Can I generate more than one shadow layer at once?", fr: "Puis-je générer plusieurs couches d'ombre en une fois ?" }, a: { en: "Not in a single pass — this tool builds one box-shadow value at a time. For a layered shadow (soft ambient + sharp contact shadow), generate each layer separately and join them with a comma in your CSS.", fr: "Pas en une seule passe — cet outil construit une valeur box-shadow à la fois. Pour une ombre en couches (ambiante douce + ombre de contact nette), générez chaque couche séparément et combinez-les avec une virgule dans votre CSS." } },
  ],
  "color-picker": [
    { q: { en: "What's the actual difference between HSL and HSV?", fr: "Quelle est la vraie différence entre HSL et HSV ?" }, a: { en: "Both describe hue, saturation and a third axis — but HSL's lightness goes from black to the pure color to white, while HSV's value goes from black to the pure color at full brightness, with saturation controlling how much white is mixed in. In practice, HSV tends to match how design tools like Photoshop let you darken a color without it turning gray.", fr: "Les deux décrivent la teinte, la saturation et un troisième axe — mais la luminosité (lightness) de HSL va du noir à la couleur pure jusqu'au blanc, tandis que la valeur de HSV va du noir à la couleur pure à pleine luminosité, la saturation contrôlant la quantité de blanc mélangée. En pratique, HSV correspond souvent à la façon dont des outils comme Photoshop permettent d'assombrir une couleur sans qu'elle vire au gris." } },
    { q: { en: "Does this tool support colors with transparency?", fr: "Cet outil gère-t-il les couleurs avec transparence ?" }, a: { en: "Not directly — the underlying browser color picker only handles opaque colors. Copy the HEX or RGB value from here and add the alpha channel yourself, either as an 8-digit hex or by switching to rgba()/hsla() syntax.", fr: "Pas directement — le sélecteur de couleur natif du navigateur ne gère que les couleurs opaques. Copiez la valeur HEX ou RGB depuis ici et ajoutez vous-même le canal alpha, soit en hexadécimal à 8 chiffres, soit en passant à la syntaxe rgba()/hsla()." } },
  ],
  "contrast-checker": [
    { q: { en: "What exactly counts as 'large text' for the relaxed 3:1 threshold?", fr: "Qu'est-ce qui compte exactement comme « grand texte » pour le seuil allégé de 3:1 ?" }, a: { en: "WCAG defines it precisely: 18pt (24px) at regular weight, or 14pt (about 18.66px) at bold weight, and nothing smaller. A 22px regular paragraph doesn't qualify — it still needs the full 4.5:1 ratio.", fr: "Le WCAG le définit précisément : 18pt (24px) en graisse normale, ou 14pt (environ 18,66px) en gras, rien de plus petit. Un paragraphe en 22px normal n'est pas éligible — il a toujours besoin du ratio complet de 4,5:1." } },
    { q: { en: "My colors pass AA — does that mean the design is accessible?", fr: "Mes couleurs passent AA — est-ce que ça veut dire que le design est accessible ?" }, a: { en: "It means this one specific check passes. Contrast ratio is one WCAG success criterion among many — color-blindness-safe palettes, focus indicators, and text spacing are separate requirements this tool doesn't check.", fr: "Ça veut dire que ce critère précis est validé. Le ratio de contraste est un critère de succès WCAG parmi beaucoup d'autres — palettes adaptées au daltonisme, indicateurs de focus, espacement du texte sont des exigences séparées que cet outil ne vérifie pas." } },
  ],
  "css-grid": [
    { q: { en: "Can this generator create a layout with a fixed sidebar and flexible content area?", fr: "Ce générateur peut-il créer une mise en page avec une barre latérale fixe et une zone de contenu flexible ?" }, a: { en: "Not directly — it only outputs uniform tracks via repeat(count, size), so every column or row in a given axis shares the same size. For a mixed layout like grid-template-columns: 240px 1fr 240px, copy the base output and edit the template-columns line by hand.", fr: "Pas directement — il ne produit que des pistes uniformes via repeat(count, size), donc chaque colonne ou ligne d'un axe partage la même taille. Pour une mise en page mixte comme grid-template-columns: 240px 1fr 240px, copiez le résultat de base et modifiez la ligne template-columns à la main." } },
    { q: { en: "Why use fr instead of percentages for column widths?", fr: "Pourquoi utiliser fr plutôt que des pourcentages pour la largeur des colonnes ?" }, a: { en: "Percentages are calculated against the container's total width, which gets complicated once gap is involved — gap space still has to come from somewhere. Fr units divide up only the leftover space after gaps and fixed tracks are already accounted for, so the math stays correct automatically.", fr: "Les pourcentages se calculent par rapport à la largeur totale du conteneur, ce qui se complique dès que le gap entre en jeu — cet espace doit bien venir de quelque part. Les unités fr ne divisent que l'espace restant une fois le gap et les pistes fixes déjà pris en compte, donc le calcul reste juste automatiquement." } },
  ],
  "css-minifier": [
    { q: { en: "Is this as safe as a build-tool minifier like cssnano?", fr: "Est-ce aussi fiable qu'un minificateur intégré à un build comme cssnano ?" }, a: { en: "For typical stylesheets, yes — comments, whitespace and redundant semicolons are removed the same way. The one edge case to watch: this tool uses text patterns rather than a real CSS parser, so a semicolon or brace inside a quoted string value could theoretically be altered. That's rare in practice but worth a visual check on unusual CSS.", fr: "Pour des feuilles de style classiques, oui — commentaires, espaces et points-virgules redondants sont retirés de la même façon. Le cas particulier à surveiller : cet outil utilise des motifs de texte plutôt qu'un vrai parseur CSS, donc un point-virgule ou une accolade dans une valeur de chaîne entre guillemets pourrait théoriquement être altéré. C'est rare en pratique, mais mérite une vérification visuelle sur du CSS inhabituel." } },
    { q: { en: "How much size reduction should I expect?", fr: "À quelle réduction de taille dois-je m'attendre ?" }, a: { en: "It depends entirely on the source — a heavily commented, indented stylesheet can shrink 30–40%, while CSS that's already tightly written might only drop 10–15%. The exact before/after character counts are shown under the output so you don't have to guess.", fr: "Ça dépend entièrement de la source — une feuille de style très commentée et indentée peut perdre 30 à 40%, tandis qu'un CSS déjà écrit de façon compacte ne baissera peut-être que de 10 à 15%. Le nombre exact de caractères avant/après est affiché sous le résultat, pas besoin de deviner." } },
  ],
  "csv-json": [
    { q: { en: "Does the CSV parser handle commas inside quoted fields correctly?", fr: "Le parseur CSV gère-t-il correctement les virgules à l'intérieur de champs entre guillemets ?" }, a: { en: "No — it splits every line on commas regardless of quoting, so a value like \"Doe, John\" inside quotes will be split into two columns instead of one. This works fine for simple exports without embedded commas, but check the output column count on anything more complex.", fr: "Non — il découpe chaque ligne sur les virgules sans tenir compte des guillemets, donc une valeur comme \"Doe, John\" entre guillemets sera scindée en deux colonnes au lieu d'une. Ça fonctionne bien pour des exports simples sans virgule intégrée, mais vérifiez le nombre de colonnes du résultat sur quelque chose de plus complexe." } },
    { q: { en: "What happens to nested objects or arrays when converting JSON to CSV?", fr: "Que deviennent les objets ou tableaux imbriqués en convertissant du JSON vers CSV ?" }, a: { en: "The converter expects a flat array of simple key-value objects. Nested objects or arrays inside a field will be stringified rather than expanded into their own columns — flatten your data first if you need each nested value in its own CSV column.", fr: "Le convertisseur attend un tableau plat d'objets clé-valeur simples. Les objets ou tableaux imbriqués dans un champ seront convertis en texte brut plutôt qu'éclatés en colonnes propres — aplatissez vos données d'abord si vous avez besoin de chaque valeur imbriquée dans sa propre colonne CSV." } },
  ],
  "deduplicate-lines": [
    { q: { en: "Does it remove lines with extra trailing spaces as duplicates?", fr: "Supprime-t-il les lignes avec des espaces de fin superflus comme des doublons ?" }, a: { en: "No — comparison is exact, character for character. \"apple\" and \"apple \" (with a trailing space) are treated as two distinct lines and both stay. Trim your data first if inconsistent spacing might be hiding duplicates.", fr: "Non — la comparaison est exacte, caractère par caractère. \"apple\" et \"apple \" (avec une espace en fin) sont traitées comme deux lignes distinctes et restent toutes les deux. Retirez les espaces de vos données d'abord si un espacement incohérent pourrait cacher des doublons." } },
    { q: { en: "Which occurrence of a duplicate does it keep — the first or the last?", fr: "Quelle occurrence d'un doublon est conservée — la première ou la dernière ?" }, a: { en: "The first one. If \"apple\" appears on line 2 and again on line 9, the line 9 copy is removed and the line 2 position is preserved in the output order.", fr: "La première. Si \"apple\" apparaît à la ligne 2 puis de nouveau à la ligne 9, la copie de la ligne 9 est supprimée et la position de la ligne 2 est préservée dans l'ordre du résultat." } },
  ],
  "diff-viewer": [
    { q: { en: "Does it highlight the specific word that changed within a line, like an IDE would?", fr: "Surligne-t-il le mot précis qui a changé dans une ligne, comme le ferait un IDE ?" }, a: { en: "No — the diff works line by line. If one word changes inside an otherwise identical line, the whole line shows as removed and re-added rather than just the changed word being highlighted.", fr: "Non — le diff fonctionne ligne par ligne. Si un mot change dans une ligne par ailleurs identique, toute la ligne s'affiche comme supprimée et rajoutée, plutôt que de surligner uniquement le mot modifié." } },
    { q: { en: "What algorithm does the diff use?", fr: "Quel algorithme utilise le diff ?" }, a: { en: "A longest-common-subsequence comparison — the same underlying approach used by git diff and the Unix diff command — which finds the minimal set of line insertions and deletions needed to turn the first text into the second.", fr: "Une comparaison par plus longue sous-séquence commune — la même approche que celle utilisée par git diff et la commande Unix diff — qui trouve l'ensemble minimal d'insertions et suppressions de lignes nécessaires pour transformer le premier texte en second." } },
  ],
  "text-diff": [
    { q: { en: "Why does the whole paragraph show as changed when I only edited one word?", fr: "Pourquoi tout le paragraphe s'affiche-t-il comme modifié alors que je n'ai changé qu'un mot ?" }, a: { en: "The comparison works line by line, and a paragraph typed as a single unbroken line counts as one line. Break your text into shorter lines — one sentence per line, for example — before pasting, so the diff can isolate just the sentence that actually changed.", fr: "La comparaison fonctionne ligne par ligne, et un paragraphe tapé sur une seule ligne ininterrompue compte comme une seule ligne. Découpez votre texte en lignes plus courtes — une phrase par ligne, par exemple — avant de le coller, pour que le diff puisse isoler juste la phrase réellement modifiée." } },
    { q: { en: "Is this suitable for comparing full legal documents?", fr: "Est-ce adapté pour comparer des documents juridiques complets ?" }, a: { en: "For spotting which paragraphs changed, yes. For a word-level redline showing exactly which clause or term was altered inside a paragraph, split the text into one sentence per line first — otherwise a single changed word marks the entire paragraph as rewritten.", fr: "Pour repérer quels paragraphes ont changé, oui. Pour une redline au niveau du mot montrant précisément quelle clause ou quel terme a été modifié dans un paragraphe, découpez d'abord le texte en une phrase par ligne — sinon un seul mot changé marque tout le paragraphe comme réécrit." } },
  ],
  "env-formatter": [
    { q: { en: "Are my section comments preserved when I format the file?", fr: "Mes commentaires de section sont-ils conservés quand je formate le fichier ?" }, a: { en: "No — the formatter only processes KEY=value entries. Comments and blank lines used to organize the file into sections are dropped from the output entirely, so treat this as a tool for cleaning the entries themselves, not for reformatting a commented file in place.", fr: "Non — le formateur ne traite que les entrées KEY=valeur. Les commentaires et lignes vides utilisés pour organiser le fichier en sections sont entièrement retirés du résultat — considérez cet outil comme un nettoyeur d'entrées, pas comme un reformateur de fichier commenté en place." } },
    { q: { en: "If a key appears twice with different values, which one does it keep?", fr: "Si une clé apparaît deux fois avec des valeurs différentes, laquelle est conservée ?" }, a: { en: "The first one it encounters, reading top to bottom — matching how most .env loaders (like dotenv) resolve duplicate keys, where the first definition wins unless the loader is explicitly configured to override.", fr: "La première rencontrée, en lisant de haut en bas — ce qui correspond à la façon dont la plupart des chargeurs .env (comme dotenv) résolvent les clés en double, où la première définition l'emporte sauf configuration explicite du chargeur pour la surcharger." } },
  ],
  "image-compressor": [
    { q: { en: "Why did my file get bigger after choosing PNG?", fr: "Pourquoi mon fichier est-il devenu plus lourd après avoir choisi le PNG ?" }, a: { en: "PNG is lossless, so it can't shrink photographic detail the way JPEG or WebP compression does. Re-encoding a compressed photo into PNG often produces a larger file — the tool shows this honestly as a '+X% larger' result rather than hiding it.", fr: "Le PNG est sans perte, il ne peut donc pas réduire le détail photographique comme le fait la compression JPEG ou WebP. Réencoder une photo déjà compressée en PNG produit souvent un fichier plus lourd — l'outil l'affiche honnêtement en « +X% plus lourd » plutôt que de le masquer." } },
    { q: { en: "What quality setting should I use for web images?", fr: "Quel réglage de qualité utiliser pour des images web ?" }, a: { en: "75–85 for WebP is a reliable starting point for photos — visually close to the original with a meaningful size reduction. Go higher (90+) for images that will be zoomed or printed, lower (50–65) for thumbnails where sharpness matters less than load speed.", fr: "75 à 85 pour le WebP est un bon point de départ pour des photos — visuellement proche de l'original avec une réduction de poids significative. Montez plus haut (90+) pour des images zoomées ou imprimées, plus bas (50-65) pour des miniatures où la netteté compte moins que la vitesse de chargement." } },
  ],
  "lorem-ipsum": [
    { q: { en: "Does clicking generate again produce different text each time?", fr: "Cliquer pour régénérer produit-il un texte différent à chaque fois ?" }, a: { en: "No — for a given word, sentence or paragraph count, the output is always identical. The word sequence is deterministic rather than randomized, which makes mockups reproducible but means you won't get fresh variation by regenerating with the same settings.", fr: "Non — pour un nombre donné de mots, phrases ou paragraphes, le résultat est toujours identique. La séquence de mots est déterministe plutôt qu'aléatoire, ce qui rend les maquettes reproductibles mais signifie que vous n'obtiendrez pas de variation en régénérant avec les mêmes réglages." } },
    { q: { en: "Where does the Lorem Ipsum text actually come from?", fr: "D'où vient réellement le texte Lorem Ipsum ?" }, a: { en: "It's a scrambled excerpt from Cicero's 45 BC text De Finibus Bonorum et Malorum, which lost its original meaning through the scrambling and has been used as placeholder text in printing and publishing since at least the 1960s.", fr: "C'est un extrait brouillé du texte De Finibus Bonorum et Malorum de Cicéron (45 av. J.-C.), qui a perdu son sens original à travers ce brouillage et sert de texte de substitution dans l'imprimerie et l'édition depuis au moins les années 1960." } },
  ],
  "og-checker": [
    { q: { en: "Why does a link preview look broken even though the page looks fine in a browser?", fr: "Pourquoi un aperçu de lien apparaît-il cassé alors que la page paraît normale dans un navigateur ?" }, a: { en: "The most common cause is a missing or relative og:image path — a browser doesn't need that tag to render the page, but Slack, Discord and social platforms rely on it specifically for the preview thumbnail. This tool surfaces exactly which og: tags are present or missing.", fr: "La cause la plus fréquente est un chemin og:image manquant ou relatif — un navigateur n'a pas besoin de cette balise pour afficher la page, mais Slack, Discord et les plateformes sociales s'appuient spécifiquement dessus pour la vignette d'aperçu. Cet outil révèle exactement quelles balises og: sont présentes ou absentes." } },
    { q: { en: "Is the URL I check sent anywhere or logged?", fr: "L'URL que je vérifie est-elle envoyée ou journalisée quelque part ?" }, a: { en: "The URL is sent to our server to fetch the page — that's unavoidable since browsers can't read another site's HTML directly. Nothing about the URL or the fetched content is stored afterward; only standard access logs are kept briefly for security, as described in the privacy policy.", fr: "L'URL est envoyée à notre serveur pour récupérer la page — c'est inévitable car un navigateur ne peut pas lire directement le HTML d'un autre site. Rien concernant l'URL ou le contenu récupéré n'est stocké ensuite ; seuls des logs d'accès standards sont conservés brièvement à des fins de sécurité, comme décrit dans la politique de confidentialité." } },
  ],
  "schema-generator": [
    { q: { en: "If the JSON-LD is valid, will it definitely show as a rich result in Google?", fr: "Si le JSON-LD est valide, apparaîtra-t-il forcément comme résultat enrichi dans Google ?" }, a: { en: "Not necessarily. Valid syntax and rich-result eligibility are different bars — Google often requires additional fields per type (like aggregateRating for Product) beyond what basic valid JSON-LD needs. Test the output in Google's Rich Results Test to see what's actually missing for eligibility.", fr: "Pas forcément. Syntaxe valide et éligibilité aux résultats enrichis sont deux barres différentes — Google exige souvent des champs supplémentaires par type (comme aggregateRating pour Product) au-delà de ce qu'un JSON-LD simplement valide nécessite. Testez le résultat dans le Rich Results Test de Google pour voir ce qui manque réellement pour l'éligibilité." } },
    { q: { en: "Which schema type should I use for a blog post?", fr: "Quel type de schema utiliser pour un article de blog ?" }, a: { en: "Article — it covers headline, description, author, publish date and URL, which matches what Google expects for standard article rich results. Use Product only for an actual purchasable item, and FAQPage only when the content genuinely is a list of questions and answers, not general body text.", fr: "Article — il couvre le titre, la description, l'auteur, la date de publication et l'URL, ce qui correspond à ce que Google attend pour les résultats enrichis d'article standard. N'utilisez Product que pour un article réellement achetable, et FAQPage uniquement quand le contenu est vraiment une liste de questions-réponses, pas du texte de corps général." } },
  ],
  "sitemap-generator": [
    { q: { en: "Does setting a high priority value actually help a page rank better?", fr: "Régler une priorité élevée aide-t-il vraiment une page à mieux se classer ?" }, a: { en: "No — Google has said for years it treats the priority field as, at best, a weak hint and largely ignores it for ranking or crawl prioritization. Don't spend time fine-tuning it; focus on an accurate lastmod date instead, which Google does use to judge whether a page needs recrawling.", fr: "Non — Google déclare depuis des années traiter le champ priority au mieux comme un indice faible et l'ignorer largement pour le classement ou la priorisation du crawl. Ne perdez pas de temps à l'affiner ; concentrez-vous plutôt sur une date lastmod exacte, que Google utilise réellement pour juger si une page mérite d'être recrawlée." } },
    { q: { en: "Can I set a different priority or changefreq for each URL?", fr: "Puis-je définir une priorité ou un changefreq différents pour chaque URL ?" }, a: { en: "Not in a single generation — this tool applies one shared value across the whole batch. For different values per URL group (e.g. homepage vs. archived pages), generate each group separately here and merge the resulting XML files by hand.", fr: "Pas en une seule génération — cet outil applique une valeur partagée à tout le lot. Pour des valeurs différentes par groupe d'URLs (page d'accueil vs pages archivées), générez chaque groupe séparément ici et fusionnez les fichiers XML résultants à la main." } },
  ],
  "slug-generator": [
    { q: { en: "Does it work with non-Latin scripts like Arabic, Russian or Chinese?", fr: "Fonctionne-t-il avec des écritures non latines comme l'arabe, le russe ou le chinois ?" }, a: { en: "Not well — the tool strips any character outside the basic Latin alphabet and digits, rather than transliterating it. A title entirely in Cyrillic or CJK characters can come out as an empty or near-empty slug. For those scripts, a dedicated transliteration library is a better fit than this tool.", fr: "Pas bien — l'outil supprime tout caractère hors de l'alphabet latin de base et des chiffres, plutôt que de le translittérer. Un titre entièrement en cyrillique ou en caractères CJK peut donner un slug vide ou presque vide. Pour ces écritures, une bibliothèque de translittération dédiée convient mieux que cet outil." } },
    { q: { en: "What happens to accented letters like é or ñ?", fr: "Que deviennent les lettres accentuées comme é ou ñ ?" }, a: { en: "They're normalized to their plain-ASCII base letter — é becomes e, ñ becomes n — using Unicode normalization to separate the letter from its accent mark, then discarding the accent. This works reliably for French, Spanish, German and Portuguese text.", fr: "Elles sont normalisées vers leur lettre ASCII de base — é devient e, ñ devient n — via une normalisation Unicode qui sépare la lettre de son accent, puis en écartant l'accent. Ça fonctionne de façon fiable pour du texte français, espagnol, allemand et portugais." } },
  ],
  "string-escape": [
    { q: { en: "Can I use the SQL escape mode instead of parameterized queries in my application?", fr: "Puis-je utiliser le mode d'échappement SQL à la place de requêtes paramétrées dans mon application ?" }, a: { en: "No — this is for safely writing a one-off query by hand, not a substitute for prepared statements in application code. Manual escaping is a fragile defense against SQL injection; always use parameterized queries or an ORM for real application code.", fr: "Non — c'est fait pour écrire une requête ponctuelle en toute sécurité à la main, pas un substitut aux instructions préparées dans du code applicatif. L'échappement manuel est une défense fragile contre l'injection SQL ; utilisez toujours des requêtes paramétrées ou un ORM pour du vrai code applicatif." } },
    { q: { en: "Why does Bash mode escape the dollar sign?", fr: "Pourquoi le mode Bash échappe-t-il le symbole dollar ?" }, a: { en: "Inside double-quoted Bash strings, $ triggers variable expansion (like $HOME) and backticks trigger command substitution. Escaping them with a backslash keeps the literal character instead of letting the shell interpret it as code.", fr: "Dans les chaînes Bash entre guillemets doubles, le $ déclenche l'expansion de variable (comme $HOME) et les backticks déclenchent la substitution de commande. Les échapper avec un antislash conserve le caractère littéral au lieu de laisser le shell l'interpréter comme du code." } },
  ],
  "svg-optimizer": [
    { q: { en: "Can optimization change how the SVG actually looks?", fr: "L'optimisation peut-elle changer l'apparence réelle du SVG ?" }, a: { en: "In edge cases, yes. SVGO's default preset is intentionally aggressive — it can merge paths or adjust attributes it considers redundant, which occasionally shifts rendering on icons with very precise strokes. Always visually check the optimized SVG before shipping it, don't assume it's pixel-identical.", fr: "Dans des cas limites, oui. Le preset par défaut de SVGO est volontairement agressif — il peut fusionner des chemins ou ajuster des attributs qu'il juge redondants, ce qui modifie parfois le rendu sur des icônes aux traits très précis. Vérifiez toujours visuellement le SVG optimisé avant de le déployer, ne présumez pas qu'il est identique au pixel près." } },
    { q: { en: "Where does the size reduction actually come from?", fr: "D'où vient réellement la réduction de poids ?" }, a: { en: "Mostly from removing markup that design tools add but browsers don't need — XML comments, editor namespace data, redundant metadata, and default attribute values that don't need to be stated explicitly. It's cleanup, not image degradation.", fr: "Surtout de la suppression de balisage que les outils de design ajoutent mais dont les navigateurs n'ont pas besoin — commentaires XML, données de namespace d'éditeur, métadonnées redondantes, et valeurs d'attributs par défaut qui n'ont pas besoin d'être déclarées explicitement. C'est du nettoyage, pas une dégradation de l'image." } },
  ],
  "zip-extractor": [
    { q: { en: "Can it open password-protected zip files?", fr: "Peut-il ouvrir des fichiers zip protégés par mot de passe ?" }, a: { en: "No — the underlying decompression library doesn't support encrypted zip entries (AES or classic ZipCrypto), so a password-protected archive will fail to read rather than prompt you for a password. Use a desktop archive manager for encrypted zips.", fr: "Non — la bibliothèque de décompression sous-jacente ne gère pas les entrées zip chiffrées (AES ou ZipCrypto classique), donc une archive protégée par mot de passe échouera à la lecture plutôt que de demander un mot de passe. Utilisez un gestionnaire d'archives de bureau pour des zip chiffrés." } },
    { q: { en: "Is there a file size limit?", fr: "Y a-t-il une limite de taille de fichier ?" }, a: { en: "No hard limit is enforced, but the whole archive is loaded into memory at once rather than streamed, so a multi-gigabyte file can hit your browser's memory ceiling on lower-end devices even if it would open fine in a desktop tool.", fr: "Aucune limite n'est imposée en dur, mais toute l'archive est chargée en mémoire d'un coup plutôt qu'en streaming, donc un fichier de plusieurs gigaoctets peut atteindre le plafond mémoire du navigateur sur des appareils moins puissants, même s'il s'ouvrirait sans problème dans un outil de bureau." } },
  ],
};

export function toolFaqItems(tool: Tool): FaqItem[] {
  const isNetwork = tool.privacy === "network";
  return [
    ...universal(tool.name, isNetwork),
    ...(SPECIFIC[tool.slug] ?? []),
  ];
}
