import type { Tool, Category } from "./types";

export const TOOLS: Tool[] = [
  /* ── FILE ── */
  { slug: "image-converter",  cat: "file",   glyph: "▣→▢", name: { fr: "Convertisseur d'images",       en: "Image Converter"            }, desc: { fr: "Déposez une image, choisissez un format, téléchargez. JPG, PNG, WebP, AVIF — redimensionnement et contrôle qualité inclus.",   en: "Drop an image, pick a format, download. JPG, PNG, WebP, AVIF — with optional resize and quality control."                            }, tags: ["jpg","png","webp","resize"],         runs: 24109 },
  { slug: "pdf-converter",    cat: "file",   glyph: "▤↔¶",                    name: { fr: "Convertisseur PDF",            en: "PDF Converter"              }, desc: { fr: "Transformez un PDF en images, ou des images en PDF. Page par page, sans envoi sur un serveur tiers.",                          en: "Turn a PDF into images, or images into a PDF, page by page. No file ever leaves your machine."                                       }, tags: ["pdf","image","png","jpg"],           runs: 19870 },
  { slug: "audio-converter",  cat: "file",   glyph: "∿♪",                     name: { fr: "Convertisseur audio",          en: "Audio Converter"            }, desc: { fr: "MP3 ↔ WAV, FLAC, AAC, OGG dans le navigateur via FFmpeg WASM. Pas de limite de taille sauf votre RAM.",                       en: "Convert MP3 ↔ WAV, FLAC, AAC, OGG in the browser using FFmpeg WASM. No file size limit beyond your RAM."                            }, tags: ["mp3","wav","flac","audio"],          runs: 8420  },
  { slug: "video-converter",  cat: "file",   glyph: "▷▶",                     name: { fr: "Convertisseur vidéo",          en: "Video Converter"            }, desc: { fr: "Ré-encodez une vidéo ou extrayez la piste audio. MP4, WebM, GIF, MOV — propulsé par FFmpeg WASM.",                            en: "Re-encode video or rip the audio track. MP4, WebM, GIF, MOV — powered by FFmpeg WASM."                                              }, tags: ["mp4","mp3","webm","gif"],            runs: 14250 },
  { slug: "pdf-merge",        cat: "file",   glyph: "≡+≡",  name: { fr: "Fusion de PDF",                en: "PDF Merge"                  }, desc: { fr: "Déposez plusieurs PDF, réordonnez-les par glisser-déposer, fusionnez en un seul fichier. Tout reste sur votre machine.",      en: "Drop several PDFs, drag to reorder, merge into one. Everything stays on your machine."                                               }, tags: ["pdf","merge","combine"],             runs: 11034 },

  /* ── DEVELOPER ── */
  { slug: "qr-generator",     cat: "dev",    glyph: "▚▞▚", name: { fr: "Générateur QR Code",           en: "QR Code Generator"          }, desc: { fr: "Collez une URL ou du texte, obtenez un QR code en SVG ou PNG. Fonctionne hors ligne.",                                        en: "Paste a URL or text, get a QR code as SVG or PNG. Works offline."                                                                    }, tags: ["qr","barcode","encode"],             runs: 9201  },
  { slug: "base64",           cat: "dev",    glyph: "b64",  name: { fr: "Encodeur Base64",              en: "Base64 Encoder"             }, desc: { fr: "Encodez du texte ou des fichiers binaires en Base64, décodez en un clic. Utile pour les data URI, JWT et pièces jointes.",   en: "Encode text or binary files to Base64, decode back in one click. Handy for data URIs, JWTs and email attachments."                  }, tags: ["encode","decode","string"],          runs: 7503  },
  { slug: "markdown-html",    cat: "dev",    glyph: "md→",                    name: { fr: "Markdown → HTML",              en: "Markdown → HTML"            }, desc: { fr: "Écrivez du Markdown à gauche, voyez le HTML propre à droite. Copiez le résultat ou téléchargez-le.",                          en: "Write Markdown on the left, see clean HTML on the right. Copy the output or download as a file."                                    }, tags: ["markdown","html","convert"],         runs: 6340  },
  { slug: "hash-generator",   cat: "dev",    glyph: "#",                      name: { fr: "Générateur de hash",           en: "Hash Generator"             }, desc: { fr: "Collez du texte ou déposez un fichier — obtenez ses empreintes MD5, SHA-1 et SHA-256.",                                       en: "Paste text or drop a file and get its MD5, SHA-1 and SHA-256 fingerprints."                                                          }, tags: ["md5","sha256","hash"],               runs: 5120  },
  { slug: "regex-tester",     cat: "dev",    glyph: "/.*/",                   name: { fr: "Testeur de regex",             en: "Regex Tester"               }, desc: { fr: "Écrivez un pattern, voyez les correspondances surlignées en temps réel. Supporte les flags (g, i, m) et les groupes nommés.", en: "Write a pattern, see matches highlighted in real time. Supports flags (g, i, m) and named groups."                                   }, tags: ["regex","match","pattern"],           runs: 7880  },
  // Désactivé : l'offre gratuite d'ip-api.com interdit l'usage commercial — en attente d'un autre fournisseur
  { slug: "ip-lookup",        cat: "dev",    glyph: "ip",   privacy: "network", comingSoon: true, name: { fr: "Recherche d'adresse IP",     en: "IP Address Lookup"          }, desc: { fr: "Entrez une IP pour voir son pays, FAI, ASN et fuseau horaire. Laissez vide pour analyser la vôtre.",                         en: "Enter any IP to see its country, ISP, ASN and timezone. Leave blank to look up your own."                                            }, tags: ["ip","geo","network"],                runs: 4310  },
  { slug: "uuid-generator",   cat: "dev",    glyph: "id",                     name: { fr: "Générateur UUID",              en: "UUID Generator"             }, desc: { fr: "Un clic génère un UUID v4 aléatoire. Besoin de plus ? Jusqu'à 25 d'un coup.",                             en: "One click generates a fresh random v4 UUID. Need more? Generate up to 25 at once."                                            }, tags: ["uuid","guid","id"],                  runs: 6090  },
  { slug: "cron-generator",   cat: "dev",    glyph: "* *",                    name: { fr: "Générateur d'expressions cron", en: "Cron Expression Generator" }, desc: { fr: "Tapez une expression cron, obtenez une explication en français clair. Ou construisez-la champ par champ.",                  en: "Type a cron expression, get a plain-English explanation. Or build one visually field by field."                                      }, tags: ["cron","schedule","crontab"],         runs: 3760  },

  /* ── TEXT ── */
  { slug: "json-formatter",   cat: "text",   glyph: "{ }", name: { fr: "Formateur JSON",               en: "JSON Formatter"             }, desc: { fr: "Collez du JSON brouillon, récupérez-le indenté et validé. Les erreurs sont signalées par numéro de ligne.",                   en: "Paste messy JSON, get it back indented and validated. Errors flagged by line number."                                                }, tags: ["json","format","validate","lint"],   runs: 18420 },
  { slug: "case-converter",   cat: "text",   glyph: "Aa",                     name: { fr: "Convertisseur de casse",       en: "Case Converter"             }, desc: { fr: "Collez du texte et choisissez une casse : MAJUSCULE, minuscule, Titre, camelCase, snake_case ou kebab-case.",               en: "Paste text and pick a case: UPPER, lower, Title, camelCase, snake_case or kebab-case."                                              }, tags: ["case","text","transform"],           runs: 9930  },
  { slug: "word-counter",     cat: "text",   glyph: "¶#",                     name: { fr: "Compteur de mots",             en: "Word / Character Counter"   }, desc: { fr: "Comptage en temps réel des mots, caractères et phrases. Estime aussi le temps de lecture.",                                  en: "Real-time word, character and sentence count — plus an estimated reading time."                                                      }, tags: ["count","words","characters"],        runs: 8210  },
  { slug: "remove-linebreaks",cat: "text",   glyph: "¶✕",                    name: { fr: "Suppression de sauts de ligne", en: "Remove Line Breaks"        }, desc: { fr: "Collez un texte avec des sauts de ligne indésirables, récupérez un bloc propre. Pratique pour copier depuis des PDF.",      en: "Paste text with unwanted line breaks, get back a clean single block. Useful when copying from PDFs."                                 }, tags: ["text","cleanup","whitespace"],       runs: 4480  },
  { slug: "text-reverser",    cat: "text",   glyph: "◀▶",                    name: { fr: "Inverseur de texte",           en: "Text Reverser"              }, desc: { fr: "Inversez les caractères, les mots ou les lignes entières. Gère correctement l'Unicode et les emojis.",                       en: "Flip characters, words or whole lines. Handles Unicode and emojis correctly."                                                        }, tags: ["reverse","text","flip"],             runs: 2980  },
  { slug: "url-encoder",      cat: "text",   glyph: "%",                      name: { fr: "Encodeur / Décodeur URL",      en: "URL Encoder / Decoder"      }, desc: { fr: "Encodez les caractères spéciaux pour les URL ou décodez une chaîne percent-encodée. Gère les URL complètes et les composants.", en: "Encode special characters for URLs or decode a percent-encoded string. Handles full URLs and individual components."                }, tags: ["url","encode","decode"],             runs: 6710  },
  { slug: "html-entities",    cat: "text",   glyph: "&#",                     name: { fr: "Encodeur d'entités HTML",      en: "HTML Entity Encoder"        }, desc: { fr: "Convertissez < > & et les caractères accentués en entités HTML — ou dans l'autre sens.",                                    en: "Convert < > & and accented characters into HTML entities — or the other way around."                                                 }, tags: ["html","entity","escape"],            runs: 3540  },

  /* ── DESIGN ── */
  { slug: "palette-generator",cat: "design", glyph: "◐◑◒", name: { fr: "Générateur de palette",        en: "Palette Generator"          }, desc: { fr: "Choisissez une couleur de base et générez une palette harmonique complète — complémentaire, triadique, analogue.",            en: "Pick a base color and generate a full harmonic palette — complementary, triadic, analogous."                                         }, tags: ["color","design","palette"],          runs: 5821  },
  { slug: "password-generator",cat:"design", glyph: "•••",                   name: { fr: "Générateur de mot de passe",   en: "Password Generator"         }, desc: { fr: "Réglez la longueur, activez les symboles et chiffres, générez. 100% côté client, jamais transmis.",                          en: "Adjust length, toggle symbols and numbers, generate. Client-side only — never transmitted."                                          }, tags: ["password","secure","random"],        runs: 13420 },
  { slug: "gradient-generator",cat:"design", glyph: "▤▦",                    name: { fr: "Générateur de dégradé CSS",    en: "Gradient Generator"         }, desc: { fr: "Choisissez des couleurs, définissez l'angle, prévisualisez en direct. Export en CSS linear-gradient ou radial-gradient.",   en: "Choose colors, set the angle, preview live. Copies as CSS linear-gradient or radial-gradient."                                       }, tags: ["gradient","css","color"],            runs: 4920  },

  /* ── SEO ── */
  { slug: "meta-preview",     cat: "seo",    glyph: "↗▭",  privacy: "network", name: { fr: "Aperçu des balises meta",    en: "Meta Tag Preview"           }, desc: { fr: "Entrez une URL et voyez son rendu sur Google, Facebook et X — avant de la partager.",                                        en: "Enter a URL and see exactly how it looks on Google, Facebook and X before you share it."                                             }, tags: ["meta","og","seo","preview"],         runs: 5260  },
  { slug: "seo-analyzer",     cat: "seo",    glyph: "✓↗",  privacy: "network", name: { fr: "Analyseur SEO",              en: "SEO Analyzer"               }, desc: { fr: "Analysez n'importe quelle page et obtenez un score basé sur le titre, la meta description, la structure des titres et le nombre de mots.", en: "Fetch any page and get a score based on title length, meta description, heading structure and word count."                    }, tags: ["seo","audit","score"],               runs: 6580  },

  /* ── FILE — coming soon ── */
  { slug: "image-compressor",  cat: "file",   glyph: "▣↓",  name: { fr: "Compresseur d'images",         en: "Image Compressor"           }, desc: { fr: "Réduire le poids d'une image sans perte visible. JPG, PNG, WebP.",         en: "Reduce image file size with minimal quality loss. JPG, PNG, WebP."         }, tags: ["compress","image","optimize"],       runs: 0 },
{ slug: "svg-optimizer",     cat: "file",   glyph: "~svg", name: { fr: "Optimiseur SVG",               en: "SVG Optimizer"              }, desc: { fr: "Nettoyer et minifier un fichier SVG. Réduction de taille sans perte.",     en: "Clean and minify SVG files. Lossless size reduction."                      }, tags: ["svg","minify","optimize"],           runs: 0 },
  { slug: "zip-extractor",     cat: "file",   glyph: "▤↓",  name: { fr: "Extracteur ZIP",               en: "ZIP Extractor"              }, desc: { fr: "Extraire et prévisualiser le contenu d'une archive ZIP.",                  en: "Extract and preview the contents of a ZIP archive."                        }, tags: ["zip","archive","extract"],           runs: 0 },

  /* ── DEVELOPER — coming soon ── */
  { slug: "jwt-decoder",       cat: "dev",    glyph: "jwt",                    name: { fr: "Décodeur JWT",                 en: "JWT Decoder"                }, desc: { fr: "Décoder et inspecter un token JWT (header, payload, signature).",          en: "Decode and inspect a JWT token (header, payload, signature)."              }, tags: ["jwt","token","auth","decode"],       runs: 0 },
  { slug: "timestamp",         cat: "dev",    glyph: "ts",                     name: { fr: "Convertisseur de timestamp",   en: "Timestamp Converter"        }, desc: { fr: "Convertir un timestamp Unix en date lisible et vice versa.",               en: "Convert Unix timestamps to human-readable dates and back."                  }, tags: ["timestamp","unix","date","time"],    runs: 0 },
  { slug: "base-converter",    cat: "dev",    glyph: "0x",                     name: { fr: "Convertisseur de base",        en: "Number Base Converter"      }, desc: { fr: "Convertir entre décimal, hexadécimal, binaire et octal.",                  en: "Convert between decimal, hexadecimal, binary and octal."                   }, tags: ["hex","binary","decimal","octal"],    runs: 0 },
  { slug: "diff-viewer",       cat: "dev",    glyph: "±",                      name: { fr: "Comparateur de texte",         en: "Diff Checker"               }, desc: { fr: "Comparer deux textes ou deux versions de code ligne par ligne. Surlignage des ajouts et suppressions.", en: "Compare two texts or two versions of code line by line. Highlights additions and removals." }, tags: ["diff","compare","text","code"],      runs: 0 },
  { slug: "css-minifier",      cat: "dev",    glyph: "{}↓",                    name: { fr: "Minificateur CSS",             en: "CSS Minifier"               }, desc: { fr: "Minifier et compresser du CSS. Suppression des commentaires et espaces.",  en: "Minify and compress CSS. Strip comments and whitespace."                   }, tags: ["css","minify","compress"],           runs: 0 },
  { slug: "env-formatter",     cat: "dev",    glyph: ".env",                   name: { fr: "Formateur .env",               en: ".env Formatter"             }, desc: { fr: "Valider, trier et nettoyer un fichier .env.",                             en: "Validate, sort and clean a .env file."                                     }, tags: ["env","dotenv","config"],             runs: 0 },
  { slug: "color-picker",      cat: "dev",    glyph: "◉",                      name: { fr: "Sélecteur de couleur",         en: "Color Picker"               }, desc: { fr: "Sélectionner une couleur et obtenir ses valeurs HEX, RGB, HSL.",          en: "Pick a color and get its HEX, RGB and HSL values."                         }, tags: ["color","hex","rgb","hsl"],           runs: 0 },

  /* ── TEXT — coming soon ── */
  { slug: "lorem-ipsum",       cat: "text",   glyph: "¶…",                     name: { fr: "Générateur Lorem Ipsum",       en: "Lorem Ipsum Generator"      }, desc: { fr: "Générer du faux texte en latin pour des maquettes.",                       en: "Generate placeholder Latin text for mockups and prototypes."               }, tags: ["lorem","placeholder","text"],        runs: 0 },
  { slug: "deduplicate-lines", cat: "text",   glyph: "¶¶✕",                   name: { fr: "Suppression des doublons",     en: "Duplicate Line Remover"     }, desc: { fr: "Supprimer les lignes en double d'une liste.",                             en: "Remove duplicate lines from a list."                                       }, tags: ["duplicate","lines","clean"],         runs: 0 },
  { slug: "csv-json",          cat: "text",   glyph: "csv",                    name: { fr: "CSV ↔ JSON",                   en: "CSV ↔ JSON"                 }, desc: { fr: "Convertir entre CSV et JSON. Détection automatique des en-têtes.",         en: "Convert between CSV and JSON. Auto-detects headers."                       }, tags: ["csv","json","convert","table"],      runs: 0 },
  { slug: "string-escape",     cat: "text",   glyph: "\\",                     name: { fr: "Échappement de chaînes",       en: "String Escape"              }, desc: { fr: "Échapper et désechapper des chaînes JS, SQL, Bash.",                      en: "Escape and unescape strings for JS, SQL and Bash."                         }, tags: ["escape","string","js","sql"],        runs: 0 },
  { slug: "slug-generator",    cat: "text",   glyph: "-_-",                    name: { fr: "Générateur de slug",           en: "Slug Generator"             }, desc: { fr: "Convertir un titre en slug URL-friendly (accents, espaces, casse).",      en: "Convert a title to a URL-friendly slug (accents, spaces, case)."           }, tags: ["slug","url","seo","text"],           runs: 0 },

  /* ── DESIGN — coming soon ── */
  { slug: "box-shadow",        cat: "design", glyph: "□▣",                     name: { fr: "Générateur box-shadow",        en: "Box Shadow Generator"       }, desc: { fr: "Créer et prévisualiser des ombres CSS box-shadow visuellement.",           en: "Create and preview CSS box-shadow visually."                               }, tags: ["shadow","css","design"],             runs: 0 },
  { slug: "border-radius",     cat: "design", glyph: "╭╮",                     name: { fr: "Générateur border-radius",     en: "Border Radius Generator"    }, desc: { fr: "Créer des formes avec border-radius et copier le CSS généré.",            en: "Create shapes with border-radius and copy the generated CSS."              }, tags: ["border","radius","css","design"],    runs: 0 },
  { slug: "favicon-generator", cat: "design", glyph: "▣16", name: { fr: "Générateur de favicon",        en: "Favicon Generator"          }, desc: { fr: "Créer un favicon PNG/ICO depuis du texte ou un SVG.",                    en: "Create a PNG/ICO favicon from text or SVG."                                }, tags: ["favicon","icon","png","ico"],        runs: 0 },
  { slug: "contrast-checker",  cat: "design", glyph: "◐✓",                     name: { fr: "Vérificateur de contraste",    en: "Color Contrast Checker"     }, desc: { fr: "Vérifier le ratio de contraste WCAG AA/AAA entre deux couleurs.",         en: "Check the WCAG AA/AAA contrast ratio between two colors."                  }, tags: ["contrast","wcag","accessibility"],   runs: 0 },
  { slug: "css-grid",          cat: "design", glyph: "⊞",   name: { fr: "Générateur CSS Grid",          en: "CSS Grid Generator"         }, desc: { fr: "Construire une grille CSS Grid visuellement et exporter le code.",         en: "Build a CSS Grid layout visually and export the code."                     }, tags: ["grid","css","layout","design"],      runs: 0 },

  /* ── SEO / MARKETING ── */
  { slug: "utm-builder",     cat: "seo",    glyph: "?utm",                   name: { fr: "Générateur UTM",             en: "UTM Builder"           }, desc: { fr: "Construisez des URLs avec paramètres UTM pour vos campagnes. Source, canal, campagne — prêtes à copier.",       en: "Build URLs with UTM parameters for your campaigns. Source, medium, campaign — ready to copy."            }, tags: ["utm","analytics","url","marketing"], runs: 0 },

  /* ── DEVELOPER ── */
  { slug: "jwt-generator",   cat: "dev",    glyph: "jwt+",                   name: { fr: "Générateur JWT",             en: "JWT Generator"         }, desc: { fr: "Signez un payload JSON en token JWT HS256 directement dans votre navigateur. La clé n'est jamais transmise.",  en: "Sign a JSON payload as an HS256 JWT token right in your browser. The secret key is never transmitted."   }, tags: ["jwt","token","auth","sign"],         runs: 0 },
  { slug: "md-table",        cat: "dev",    glyph: "|—|",                    name: { fr: "Tableau Markdown",           en: "Markdown Table"        }, desc: { fr: "Créez un tableau Markdown visuellement — ajoutez lignes, colonnes et définissez l'alignement par colonne.",    en: "Build a Markdown table visually — add rows, columns and set per-column alignment."                        }, tags: ["markdown","table","text"],           runs: 0 },
  { slug: "toml-json",       cat: "dev",    glyph: "toml",                   name: { fr: "TOML ↔ JSON",                en: "TOML ↔ JSON"           }, desc: { fr: "Convertissez entre TOML et JSON en un clic. Idéal pour les configs Rust, Go, Cargo et Hugo.",                 en: "Convert between TOML and JSON in one click. Great for Rust, Go, Cargo and Hugo config files."            }, tags: ["toml","json","convert","config"],    runs: 0 },
  { slug: "headers-checker", cat: "dev",    glyph: "H:✓", privacy: "network", name: { fr: "Vérificateur de headers",  en: "HTTP Headers Checker"  }, desc: { fr: "Analysez les headers de sécurité d'une URL : CSP, HSTS, X-Frame-Options… avec une note globale A–F.",        en: "Analyze the security headers of any URL: CSP, HSTS, X-Frame-Options and more, with an A–F letter grade." }, tags: ["headers","security","csp","hsts"],   runs: 0 },

  /* ── TEXT ── */
  { slug: "readability",     cat: "text",   glyph: "¶✓",                    name: { fr: "Score de lisibilité",        en: "Readability Score"     }, desc: { fr: "Collez un texte, obtenez son score Flesch-Kincaid et l'indice Gunning Fog. Utile pour les rédacteurs et éditeurs.",         en: "Paste text and get its Flesch-Kincaid reading ease and Gunning Fog index. Useful for writers hitting readability targets."        }, tags: ["readability","text","flesch","seo"], runs: 0 },

  /* ── SEO — coming soon ── */
  { slug: "robots-txt",        cat: "seo",    glyph: "🤖",                     name: { fr: "Générateur robots.txt",        en: "Robots.txt Generator"       }, desc: { fr: "Générer un fichier robots.txt avec règles par agent et sitemap.",         en: "Generate a robots.txt file with per-agent rules and sitemap."              }, tags: ["robots","seo","crawl"],              runs: 0 },
  { slug: "sitemap-generator", cat: "seo",    glyph: "⊞↗",                     name: { fr: "Générateur de sitemap",        en: "Sitemap Generator"          }, desc: { fr: "Générer un sitemap XML depuis une liste d'URLs.",                         en: "Generate an XML sitemap from a list of URLs."                              }, tags: ["sitemap","xml","seo"],               runs: 0 },
  { slug: "schema-generator",  cat: "seo",    glyph: "{ld}",                   name: { fr: "Générateur Schema Markup",     en: "Schema Markup Generator"    }, desc: { fr: "Générer du JSON-LD structuré (Article, Product, FAQ, BreadcrumbList).",  en: "Generate structured JSON-LD (Article, Product, FAQ, BreadcrumbList)."      }, tags: ["schema","json-ld","seo","rich"],     runs: 0 },
  { slug: "og-checker",        cat: "seo",    glyph: "og✓",                    privacy: "network", name: { fr: "Vérificateur Open Graph",    en: "Open Graph Checker"         }, desc: { fr: "Vérifier et valider les balises Open Graph d'une page web.",             en: "Check and validate Open Graph tags on any web page."                       }, tags: ["og","opengraph","meta","seo"],       runs: 0 },
];

export const POPULAR_TAGS: readonly string[] = (() => {
  const freq = new Map<string, number>();
  for (const tool of TOOLS) {
    if (!tool.comingSoon) {
      for (const tag of tool.tags) freq.set(tag, (freq.get(tag) ?? 0) + 1);
    }
  }
  return [...freq.entries()].sort((a, b) => b[1] - a[1]).slice(0, 7).map(([tag]) => tag);
})();

/**
 * Noms des outils réseau actifs (requête côté serveur), pour les textes qui les
 * énumèrent : FAQ, À propos, CGU, llms.txt. Calculé pour ne jamais dériver.
 */
export function networkToolNames(lang: "fr" | "en"): string[] {
  return TOOLS.filter((t) => t.privacy === "network" && !t.comingSoon).map((t) => t.name[lang]);
}

export const CATEGORIES: Category[] = [
  { id: "all",    label: { fr: "Tous",        en: "All"       }, glyph: "*"   },
  { id: "file",   label: { fr: "Fichiers",    en: "File"      }, glyph: "▣"   },
  { id: "dev",    label: { fr: "Développeur", en: "Developer" }, glyph: "</>" },
  { id: "text",   label: { fr: "Texte",       en: "Text"      }, glyph: "¶"   },
  { id: "design", label: { fr: "Design",      en: "Design"    }, glyph: "◐"   },
  { id: "seo",    label: { fr: "Marketing",   en: "Marketing" }, glyph: "↗"   },
];
