"use client";

import { useState, useCallback } from "react";
import { useLang } from "@/components/providers/I18nProvider";
import { t } from "@/lib/i18n";
import { useCopy } from "@/hooks/useCopy";
import { OptionsBar, OptBlock, Toggle } from "@/components/workspace/OptionsBar";
import { Pane, PaneBtn } from "@/components/workspace/Pane";

const SAMPLE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
  <!-- Generated by Figma -->
  <title>Icon</title>
  <g id="Layer_1" data-name="Layer 1">
    <circle cx="50" cy="50" r="40" fill="#00e08a" stroke="none" stroke-width="0"/>
    <rect x="30" y="30" width="40" height="40" fill="white" opacity="1.0"/>
  </g>
</svg>`;

type OptResult = { output: string; before: number; after: number } | null;

export function SvgOptimizer() {
  const { lang } = useLang();
  const i = t(lang);
  const [input, setInput] = useState(SAMPLE_SVG);
  const [result, setResult] = useState<OptResult>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [removeComments, setRemoveComments] = useState(true);
  const [removeMetadata, setRemoveMetadata] = useState(true);
  const [removeEditorsNS, setRemoveEditorsNS] = useState(true);
  const { copy, copied } = useCopy();

  const optimize = useCallback(async () => {
    if (!input.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const { optimize: svgoOptimize } = await import("svgo/browser");
      const svgoResult = svgoOptimize(input, {
        plugins: [
          "preset-default",
          ...(removeComments  ? ["removeComments"]      : []),
          ...(removeMetadata  ? ["removeMetadata"]      : []),
          ...(removeEditorsNS ? ["removeEditorsNSData"] : []),
        ],
      } as Parameters<typeof svgoOptimize>[1]);

      setResult({
        output: svgoResult.data,
        before: new Blob([input]).size,
        after: new Blob([svgoResult.data]).size,
      });
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }, [input, removeComments, removeMetadata, removeEditorsNS]);

  const saving = result ? Math.round((1 - result.after / result.before) * 100) : null;

  return (
    <section className="mb-10">
      <OptionsBar
        action={
          <div className="flex gap-2">
            {result && (
              <button
                onClick={() => copy(result.output)}
                className="px-[14px] py-2 font-mono text-[12px] text-dim border border-line rounded-[3px] hover:text-brand hover:border-brand-mid transition-colors"
              >
                {copied ? "✓" : i.copy}
              </button>
            )}
            <button
              onClick={optimize}
              disabled={loading || !input.trim()}
              className="px-[18px] py-2 bg-brand text-bg font-mono text-[12px] font-semibold tracking-[0.04em] rounded-[3px] hover:brightness-110 transition-all disabled:opacity-40"
            >
              {loading ? "…" : i.optimizeBtn}
            </button>
          </div>
        }
      >
        <OptBlock label={i.options}>
          <div className="flex gap-4">
            {([
              { label: "comments",  on: removeComments,  set: setRemoveComments  },
              { label: "metadata",  on: removeMetadata,  set: setRemoveMetadata  },
              { label: "editor NS", on: removeEditorsNS, set: setRemoveEditorsNS },
            ] as const).map(({ label, on, set }) => (
              <label key={label} className={`flex items-center gap-2 font-mono text-[11px] cursor-pointer transition-colors ${on ? "text-brand" : "text-dim"}`}>
                <Toggle on={on} onChange={set} />
                {label}
              </label>
            ))}</div>
        </OptBlock>
      </OptionsBar>

      <div className="grid grid-cols-1 md:grid-cols-2 border border-line">
        <Pane
          title="SVG input"
          ext="svg"
          actions={<PaneBtn onClick={() => { setInput(""); setResult(null); }}>{i.clearInput}</PaneBtn>}
          className="border-r border-line"
        >
          <div className="flex-1 p-[14px] bg-bg-code">
            <textarea
              value={input}
              onChange={(e) => { setInput(e.target.value); setResult(null); }}
              className="w-full h-full min-h-[320px] bg-transparent font-mono text-[12px] text-fg leading-[1.65] outline-none resize-none"
              spellCheck={false}
            />
          </div>
        </Pane>

        <Pane
          title={`SVG output${saving !== null ? ` — −${saving}%` : ""}`}
          ext="svg"
          actions={
            result && (
              <PaneBtn onClick={() => copy(result.output)}>{i.copy}</PaneBtn>
            )
          }
        >
          <div className="flex-1 p-[14px] bg-bg-code">
            {error ? (
              <p className="font-mono text-[12px] text-danger">✕ {error}</p>
            ) : result ? (
              <pre className="font-mono text-[12px] text-fg-1 leading-[1.65] whitespace-pre-wrap min-h-[320px]">
                {result.output}
              </pre>
            ) : (
              <span className="font-mono text-[12px] text-dim-2">
                {i.resultHere}
              </span>
            )}
          </div>
          {result && (
            <div className="px-[14px] py-[8px] border-t border-line bg-bg flex items-center gap-6">
              {[
                { label: "before", val: `${result.before} B` },
                { label: "after",  val: `${result.after} B` },
                { label: "saved",  val: `${saving}%`, accent: true },
              ].map(({ label, val, accent }) => (
                <div key={label} className="flex items-center gap-2">
                  <span className="font-mono text-[10px] text-dim">{label}</span>
                  <span className={`font-mono text-[12px] font-semibold ${accent ? "text-ok" : "text-fg"}`}>{val}</span>
                </div>
              ))}
            </div>
          )}
        </Pane>
      </div>

      <div className="border border-line border-t-0 px-[14px] py-2 bg-bg font-mono text-[11px] text-dim">
        {i.localSvgo}
      </div>
    </section>
  );
}
